version: '3.1'

services:
  db:
      image: mysql:5.7
      ports:
          - "3306:3306"
      environment:
          MYSQL_ROOT_USER: admin
          MYSQL_ROOT_PASSWORD: pass
          MYSQL_PASSWORD: pass
          MYSQL_DATABASE: bookdb
          MYSQL_PORT: 3306